name: "Creates Batch Release PR"

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  create_release_pr:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Set up tools
        run: dart pub get
        working-directory: ${{ github.workspace }}/script/tool
    # Give some time for LUCI checks to start becoming populated.
    # Because of latency in Github Webhooks, we need to wait for a while
    # before being able to look at checks scheduled by LUCI.
      - name: Give webhooks a minute
        run: sleep 60s
        shell: bash
      - name: create batch release PR
        run: |
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.USER_EMAIL }}
          dart ./script/tool/lib/src/main.dart batch
